name: Deploy to Firebase Hosting on staging
'on':
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install npm modules
        run: yarn install
      - name: Build app
        run: yarn predeploy
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_SCALAMATSURI_2024_WEB_STAGE }}
          channelId: live
          projectId: scalamatsuri-2024-web-stage
